/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arrays1;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileAttribute;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arch
 */
public class Mian extends javax.swing.JFrame {

	DefaultTableModel tm = new DefaultTableModel();
	ArrayList<String> input = new ArrayList<String>();
	int countWords = 0;
	int lastWord = 0;
	double[] array17 = new double[8];
	int last_array17_index = 0;

	/**
	 * Creates new form Mian
	 */
	public Mian() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane_Part1 = new javax.swing.JTabbedPane();
        jPanel_Exercise17Part1 = new javax.swing.JPanel();
        jLabel_exercise17Part1 = new javax.swing.JLabel();
        jLabel_entered17Part1 = new javax.swing.JLabel();
        jLabel_inputArray = new javax.swing.JLabel();
        jTextField_input = new javax.swing.JTextField();
        jLabel_guess17Part1 = new javax.swing.JLabel();
        jButton_accept17Part1 = new javax.swing.JButton();
        jLabel_inputAvarage = new javax.swing.JLabel();
        jPanel_Eexercise42Part1 = new javax.swing.JPanel();
        jLabel_exercise42Part1 = new javax.swing.JLabel();
        calculate42Part1 = new javax.swing.JButton();
        jLabel_outputPrices = new javax.swing.JLabel();
        jLabel_outputMin = new javax.swing.JLabel();
        jLabel_outputMax = new javax.swing.JLabel();
        jPanel_Exercise67Part1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_outputMinAExercise67Part1 = new javax.swing.JLabel();
        jLabel_outputMinBExercise67Part1 = new javax.swing.JLabel();
        jLabel_outputMinCExercise67Part1 = new javax.swing.JLabel();
        jLabel_outputAvarageExercise67Part1 = new javax.swing.JLabel();
        accept67_jButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel_outputMinB = new javax.swing.JLabel();
        jLabel_outputCexercise67Part1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        calculate17_jButtton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel_outputRowExercise17Part2 = new javax.swing.JLabel();
        jLabel_outputColumnExercise17Part2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel_exercise42aPart2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_captionOutputMatrixExercise42aPart2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_outputMatrixExercise42aPart2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel_exercise17Part3 = new javax.swing.JLabel();
        jTextField_inputStringExercise17Part3 = new javax.swing.JTextField();
        jButton_acceptExercise17Part3 = new javax.swing.JButton();
        jLabel_outputExercise17Part3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel_exercise42Part3 = new javax.swing.JLabel();
        jTextField_inputStringExercise42Part3 = new javax.swing.JTextField();
        jButton_acceptExercise42Part3 = new javax.swing.JButton();
        jLabel_outputExercise42Part3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel_exercise67Part3 = new javax.swing.JLabel();
        jTextField_input1Exercise67Part3 = new javax.swing.JTextField();
        jButton_acceptExercise67Part3 = new javax.swing.JButton();
        jTextField_input2Exercise67Part3 = new javax.swing.JTextField();
        jTextField_input3ExercisePart3 = new javax.swing.JTextField();
        jLabel_output1Exercise67Part3 = new javax.swing.JLabel();
        jLabel_output2Exercise67Part3 = new javax.swing.JLabel();
        jLabel_output3Exercise67Part3 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jLabel_exercise17Part4 = new javax.swing.JLabel();
        jButton_doExercise17Part4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_outputExercise17Part4 = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel_exercise42Part4 = new javax.swing.JLabel();
        jButton_doExercise42Part4 = new javax.swing.JButton();
        jLabel_outputCaptionWeightExercise42Part4 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel_outputOtherCaptionExercise42Part4 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_outputWeightExercise42Part4 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_outputOtherExercise42Part4 = new javax.swing.JTable();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel19 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_exercise17Part1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_exercise17Part1.setText("<html>Заполнить массив А[1..8] числами, вводимыми с клавиатуры.Найти среднее арифметическое положительных элементов.</html>");
        jLabel_exercise17Part1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel_entered17Part1.setText("Entered: 0");

        jLabel_inputArray.setText("Array: ");

        jLabel_guess17Part1.setText("Enter next number");

        jButton_accept17Part1.setText("Accept");
        jButton_accept17Part1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_accept17Part1ActionPerformed(evt);
            }
        });

        jLabel_inputAvarage.setText("Avarage: ");

        javax.swing.GroupLayout jPanel_Exercise17Part1Layout = new javax.swing.GroupLayout(jPanel_Exercise17Part1);
        jPanel_Exercise17Part1.setLayout(jPanel_Exercise17Part1Layout);
        jPanel_Exercise17Part1Layout.setHorizontalGroup(
            jPanel_Exercise17Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Exercise17Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Exercise17Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Exercise17Part1Layout.createSequentialGroup()
                        .addComponent(jLabel_exercise17Part1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel_Exercise17Part1Layout.createSequentialGroup()
                        .addComponent(jLabel_guess17Part1)
                        .addGap(37, 37, 37)
                        .addComponent(jTextField_input, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton_accept17Part1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jLabel_entered17Part1)
                        .addGap(159, 159, 159))
                    .addGroup(jPanel_Exercise17Part1Layout.createSequentialGroup()
                        .addGroup(jPanel_Exercise17Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_inputArray)
                            .addComponent(jLabel_inputAvarage))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_Exercise17Part1Layout.setVerticalGroup(
            jPanel_Exercise17Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Exercise17Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise17Part1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_Exercise17Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_guess17Part1)
                    .addComponent(jTextField_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_entered17Part1)
                    .addComponent(jButton_accept17Part1))
                .addGap(54, 54, 54)
                .addComponent(jLabel_inputArray)
                .addGap(18, 18, 18)
                .addComponent(jLabel_inputAvarage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_Part1.addTab("17", jPanel_Exercise17Part1);

        jLabel_exercise42Part1.setText("<html>В массиве хранятся цены на 20 видов товаров. С помощью датчика<br/> случайных чисел заполнить массив целыми значениями, лежащими в диапазоне от<br/> 50 до 700 включительно. Определить цену самого дешевого и самого <br/>дорогого товаров.</html>");

        calculate42Part1.setText("Calculate");
        calculate42Part1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate42Part1ActionPerformed(evt);
            }
        });

        jLabel_outputPrices.setText("Prices: ");

        jLabel_outputMin.setText("Min: ");

        jLabel_outputMax.setText("Max: ");

        javax.swing.GroupLayout jPanel_Eexercise42Part1Layout = new javax.swing.GroupLayout(jPanel_Eexercise42Part1);
        jPanel_Eexercise42Part1.setLayout(jPanel_Eexercise42Part1Layout);
        jPanel_Eexercise42Part1Layout.setHorizontalGroup(
            jPanel_Eexercise42Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Eexercise42Part1Layout.createSequentialGroup()
                .addGroup(jPanel_Eexercise42Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Eexercise42Part1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_outputPrices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_Eexercise42Part1Layout.createSequentialGroup()
                        .addGroup(jPanel_Eexercise42Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_exercise42Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_Eexercise42Part1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_Eexercise42Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_outputMin)
                                    .addComponent(jLabel_outputMax))))
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel_Eexercise42Part1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(calculate42Part1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Eexercise42Part1Layout.setVerticalGroup(
            jPanel_Eexercise42Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Eexercise42Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise42Part1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel_outputPrices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_outputMin)
                .addGap(12, 12, 12)
                .addComponent(jLabel_outputMax)
                .addGap(18, 18, 18)
                .addComponent(calculate42Part1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane_Part1.addTab("42", jPanel_Eexercise42Part1);

        jLabel5.setText("<html>Заданы массивы а[1...20], b[1...10] и c[1...15]. Найти среднее арифметическое минимальных элементов массива (использовать процедуру формирования массива и процедуру определения минимального элемента).</html>");

        jLabel_outputMinAExercise67Part1.setText("Min a:");

        jLabel_outputMinBExercise67Part1.setText("Min b: ");

        jLabel_outputMinCExercise67Part1.setText("Min c: ");

        jLabel_outputAvarageExercise67Part1.setText("Avarage: ");

        accept67_jButton.setText("Calculate");
        accept67_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept67_jButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("a: ");

        jLabel_outputMinB.setText("b: ");

        jLabel_outputCexercise67Part1.setText("c: ");

        javax.swing.GroupLayout jPanel_Exercise67Part1Layout = new javax.swing.GroupLayout(jPanel_Exercise67Part1);
        jPanel_Exercise67Part1.setLayout(jPanel_Exercise67Part1Layout);
        jPanel_Exercise67Part1Layout.setHorizontalGroup(
            jPanel_Exercise67Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel_Exercise67Part1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Exercise67Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Exercise67Part1Layout.createSequentialGroup()
                        .addGroup(jPanel_Exercise67Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_outputMinBExercise67Part1)
                            .addComponent(jLabel_outputMinCExercise67Part1))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel_Exercise67Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_outputMinB, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                            .addComponent(jLabel_outputCexercise67Part1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel_Exercise67Part1Layout.createSequentialGroup()
                        .addComponent(jLabel_outputMinAExercise67Part1)
                        .addGap(102, 102, 102)
                        .addComponent(accept67_jButton))
                    .addComponent(jLabel_outputAvarageExercise67Part1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel_Exercise67Part1Layout.setVerticalGroup(
            jPanel_Exercise67Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Exercise67Part1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Exercise67Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_outputMinAExercise67Part1)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Exercise67Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_outputMinBExercise67Part1)
                    .addComponent(jLabel_outputMinB, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Exercise67Part1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_outputMinCExercise67Part1)
                    .addComponent(jLabel_outputCexercise67Part1))
                .addGap(26, 26, 26)
                .addComponent(jLabel_outputAvarageExercise67Part1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(accept67_jButton)
                .addGap(35, 35, 35))
        );

        jTabbedPane_Part1.addTab("67", jPanel_Exercise67Part1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Part1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane_Part1)
        );

        jTabbedPane1.addTab("Раздел 1", jPanel1);

        jLabel12.setText("<html>Составить программу для определения номера строки и номера столбца прямоугольной матрицы, на<br/> пересечении которых находится наименьший по абсолютной величине элемент этой матрицы.</html>");

        calculate17_jButtton.setText("calculate");
        calculate17_jButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate17_jButttonActionPerformed(evt);
            }
        });

        jLabel13.setText("Array: ");

        jLabel_outputRowExercise17Part2.setText("Row: ");

        jLabel_outputColumnExercise17Part2.setText("Column: ");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel42.setText("Columns: ");

        jLabel43.setText("Rows: ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(calculate17_jButtton))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel_outputRowExercise17Part2)
                            .addComponent(jLabel_outputColumnExercise17Part2)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel43)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculate17_jButtton)
                .addGap(9, 9, 9)
                .addComponent(jLabel_outputRowExercise17Part2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_outputColumnExercise17Part2)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addGap(269, 269, 269))
        );

        jTabbedPane3.addTab("17", jPanel8);

        jLabel_exercise42aPart2.setText("<html>Сформировать матрицу вида:<br/>0 0 0 0 1 <br/>0 0 0 2 0<br/> 0 0 3 0 0<br/> 0 4 0 0 0<br/> 5 0 0 0 0</html>");

        jButton1.setText("Form matrix");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_captionOutputMatrixExercise42aPart2.setText("Matrix: ");

        jTable_outputMatrixExercise42aPart2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane3.setViewportView(jTable_outputMatrixExercise42aPart2);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel_exercise42aPart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_captionOutputMatrixExercise42aPart2)
                        .addGap(71, 71, 71)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(150, 347, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise42aPart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_captionOutputMatrixExercise42aPart2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("42a", jPanel9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Раздел 2", jPanel2);

        jLabel_exercise17Part3.setText("Изменить введенную строку, уменьшив все ее цифры, кроме 0, на 1.");

        jButton_acceptExercise17Part3.setText("Accept");
        jButton_acceptExercise17Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_acceptExercise17Part3ActionPerformed(evt);
            }
        });

        jLabel_outputExercise17Part3.setText("Output: ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise17Part3)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_acceptExercise17Part3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jTextField_inputStringExercise17Part3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel_outputExercise17Part3))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise17Part3)
                .addGap(18, 18, 18)
                .addComponent(jTextField_inputStringExercise17Part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_acceptExercise17Part3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_outputExercise17Part3)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("17", jPanel10);

        jLabel_exercise42Part3.setText("Составить программу ,заменяющую окончания строк: \"ion\" -> \"ed\"");

        jButton_acceptExercise42Part3.setText("Accept");
        jButton_acceptExercise42Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_acceptExercise42Part3ActionPerformed(evt);
            }
        });

        jLabel_outputExercise42Part3.setText("Output: ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise42Part3)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton_acceptExercise42Part3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addComponent(jTextField_inputStringExercise42Part3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel_outputExercise42Part3))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise42Part3)
                .addGap(18, 18, 18)
                .addComponent(jTextField_inputStringExercise42Part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_acceptExercise42Part3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_outputExercise42Part3)
                .addContainerGap(406, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("42", jPanel11);

        jLabel_exercise67Part3.setText("<html>Преобразовать три введенные строки, чтобы после каждой цифры <br/>следовал символ  ̳!‘ (создать процедуру, вставляющую пробел после каждой цифры в строке)</html>");

        jTextField_input1Exercise67Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input1Exercise67Part3ActionPerformed(evt);
            }
        });

        jButton_acceptExercise67Part3.setText("Accept");
        jButton_acceptExercise67Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_acceptExercise67Part3ActionPerformed(evt);
            }
        });

        jTextField_input2Exercise67Part3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input2Exercise67Part3ActionPerformed(evt);
            }
        });

        jTextField_input3ExercisePart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_input3ExercisePart3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_exercise67Part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_acceptExercise67Part3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jTextField_input1Exercise67Part3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_input2Exercise67Part3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_input3ExercisePart3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_output1Exercise67Part3, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                            .addComponent(jLabel_output2Exercise67Part3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_output3Exercise67Part3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise67Part3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_input1Exercise67Part3)
                    .addComponent(jLabel_output1Exercise67Part3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_input2Exercise67Part3)
                    .addComponent(jLabel_output2Exercise67Part3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_output3Exercise67Part3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_input3ExercisePart3))
                .addGap(27, 27, 27)
                .addComponent(jButton_acceptExercise67Part3)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("67", jPanel12);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4))
        );

        jTabbedPane1.addTab("Раздел 3", jPanel3);

        jLabel_exercise17Part4.setText("<html>Создать файл, содержащий значения x (-pi x  pi, h= pi/10) и значения функции y= sin (x) и y= cos (x). <br/>Вывести на экран данные в виде таблицы.</html>");

        jButton_doExercise17Part4.setText("Calculate");
        jButton_doExercise17Part4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise17Part4ActionPerformed(evt);
            }
        });

        jTable_outputExercise17Part4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "X", "sinx", "cosx"
            }
        ));
        jScrollPane4.setViewportView(jTable_outputExercise17Part4);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_exercise17Part4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton_doExercise17Part4))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise17Part4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_doExercise17Part4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 294, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("17", jPanel13);

        jLabel_exercise42Part4.setText("<html>Создать файл, содержащий данные о багаже пассажиров: фамилия пассажира; <br/>количество вещей; общий вес.Записать в новый файл тех  36  пассажиров, <br/>общий вес вещей которых превышает 36кг (одновременно вывести данные на экран).</html>");

        jButton_doExercise42Part4.setText("Complete");
        jButton_doExercise42Part4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_doExercise42Part4ActionPerformed(evt);
            }
        });

        jLabel_outputCaptionWeightExercise42Part4.setText("Weight > 36");

        jLabel_outputOtherCaptionExercise42Part4.setText("Other");

        jTable_outputWeightExercise42Part4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Second name", "Count of stuffs", "Weight"
            }
        ));
        jScrollPane5.setViewportView(jTable_outputWeightExercise42Part4);

        jTable_outputOtherExercise42Part4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Second name", "Count of stuffs", "Weight"
            }
        ));
        jScrollPane6.setViewportView(jTable_outputOtherExercise42Part4);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel_exercise42Part4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jButton_doExercise42Part4))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_outputCaptionWeightExercise42Part4))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel34))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_outputOtherCaptionExercise42Part4)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_exercise42Part4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_doExercise42Part4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_outputCaptionWeightExercise42Part4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel34))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jLabel_outputOtherCaptionExercise42Part4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("42", jPanel14);

        jTabbedPane1.addTab("Раздел 4", jTabbedPane5);

        jLabel35.setText("<html>17.В трехзначном числе, все цифры которого<br/> нечетны, зачеркнули среднюю цифру. Оказалось, что полученное<br/> двузначное число является делителем исходного числа. Найти все такие трехзначные числа.</html");

        jButton7.setText("Calculate");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel36.setText("Result: ");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton7))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("17", jPanel15);

        jLabel37.setText("<html>42.Составить программу расчета роста по месяцам в течение двух лет<br/> банковского вклада. Программа запрашивает с защитой от неверного ввода данных следующую информацию:<br/> - начальный размер вклада ( 5000...30000 ),<br/> - размер процентной ставки по вкладу (0.5% ... 2.5%),<br/> - размер периодических платежей (от 0.5% до 5% от начального вклада).<br/> Вывести таблицу роста вклада по месяцам<br/>, а также определить количества месяцев, необходимые для роста начальной суммы вклада на 50%</html>");

        jLabel38.setText("Начальный вклад");

        jLabel39.setText("Процентная ставка");

        jLabel40.setText("Размер периодических платежей");

        jButton8.setText("Рассчитать");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel41.setText("Через 2 года");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel40))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(jTextField8)
                                    .addComponent(jTextField7)))))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton8))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel41)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("42", jPanel16);

        jTabbedPane1.addTab("Раздел 5", jTabbedPane6);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Столбец 1", "Столбец 2", "Столбец 3", "Столбец 4", "Столбец 5", "Стобец 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton9.setText("Calculate");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton9)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Массивы", jPanel17);

        jButton10.setText("Пример7");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel44.setText("Result:");

        jButton11.setText("Example9");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTextField13.setEnabled(false);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jLabel45.setText("Entered: ");

        jLabel46.setText("Result:");

        jLabel47.setText("Count words: ");

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jList2);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel44)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel46))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel45))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel18Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(156, 156, 156))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jLabel44)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11)
                    .addComponent(jLabel45)
                    .addComponent(jLabel47)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Строки", jPanel18);

        jButton12.setText("jButton12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jTextField15.setText("jTextField15");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(117, 117, 117))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(447, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Символы", jPanel19);

        jTabbedPane1.addTab("Практика", jTabbedPane7);

        jMenu1.setText("File");

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setText("Info");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	public static Path createFile(String path_of, String pathOfDirectory, String name) {
		Path path = Path.of(path_of);
		Path directory = Path.of(pathOfDirectory);
		if (!Files.exists(path)) {
			try {
				path = Files.createFile(directory.resolve(name));
			} catch (IOException ex) {
				Logger.getLogger(Mian.class.getName()).log(Level.SEVERE, null, ex);
				return null;
			}
		}
		return path;
	}

	public static void writeFile(Path path, String to_write) {
		try {
			Files.writeString(path, to_write, StandardCharsets.UTF_8);
		} catch (IOException ex) {
			Logger.getLogger(Mian.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	public static void createAndWriteFile(String path_of, String path_of_directory, String name, String to_write) {
		Path path = createFile(path_of, path_of_directory, name);
		if (path != null) {
			writeFile(path, to_write);
		}
	}

    private void jButton_doExercise17Part4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise17Part4ActionPerformed
		String to_write = "";
		Double[][] data = new Double[21][3];

		// Filling a data
		int current_str_number = 0;
		for (Double x = -Math.PI; x < Math.PI + Math.PI / 10; x += Math.PI / 10) {
			Double sinx = Math.sin(x);
			Double cosx = Math.cos(x);

			data[current_str_number][0] = x;
			data[current_str_number][1] = sinx;
			data[current_str_number][2] = cosx;
			current_str_number++;

			// Preparing to writing in file
			to_write += x.toString() + " "
					+ sinx.toString() + " "
					+ cosx.toString() + "\n";

		}

		createAndWriteFile("/tmp/file.txt", "/tmp", "file.txt", to_write);
		ShowOnTable.showMatrix(data, jTable_outputExercise17Part4);
    }//GEN-LAST:event_jButton_doExercise17Part4ActionPerformed

    private void jTextField_input3ExercisePart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input3ExercisePart3ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input3ExercisePart3ActionPerformed

    private void jTextField_input2Exercise67Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input2Exercise67Part3ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input2Exercise67Part3ActionPerformed

    private void jButton_acceptExercise67Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_acceptExercise67Part3ActionPerformed
		exercise67strings(jTextField_input1Exercise67Part3, jLabel_output1Exercise67Part3);
		exercise67strings(jTextField_input2Exercise67Part3, jLabel_output2Exercise67Part3);
		exercise67strings(jTextField_input3ExercisePart3, jLabel_output3Exercise67Part3);
    }//GEN-LAST:event_jButton_acceptExercise67Part3ActionPerformed

    private void jTextField_input1Exercise67Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_input1Exercise67Part3ActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_jTextField_input1Exercise67Part3ActionPerformed

    private void jButton_acceptExercise42Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_acceptExercise42Part3ActionPerformed
		String input = jTextField_inputStringExercise42Part3.getText();
		String output = input;

		// Check there is "ion" at the end of string
		if (input.endsWith("ion")) {
			output = input.substring(0, input.length() - 3) + "ed";
		}

		jLabel_outputExercise42Part3.setText(output);
    }//GEN-LAST:event_jButton_acceptExercise42Part3ActionPerformed

    private void jButton_acceptExercise17Part3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_acceptExercise17Part3ActionPerformed
		String input = jTextField_inputStringExercise17Part3.getText();
		String output = input;

		// Transformation of input
		for (int i = 0; i < input.length(); i++) {
			Integer number = tryParse(String.valueOf(input.charAt(i)));
			if (number != null) {
				if (number != 0) {
					number--;
				}
				output = replaceAt(input, i, number.toString());
			}
		}

		jLabel_outputExercise17Part3.setText(output);
    }//GEN-LAST:event_jButton_acceptExercise17Part3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		int[][] array = new int[][]{
			new int[]{0, 0, 0, 0, 1},
			new int[]{0, 0, 0, 2, 0},
			new int[]{0, 0, 3, 0, 0},
			new int[]{0, 4, 0, 0, 0},
			new int[]{5, 0, 0, 0, 0}
		};
		ShowOnTable.showMatrix(array, jTable_outputMatrixExercise42aPart2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calculate17_jButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate17_jButttonActionPerformed
		int WIDTH = InputFromTextField.getFromIntTextField(jTextField10);
		int HEIGHT = InputFromTextField.getFromIntTextField(jTextField11);
		int MIN = -10;
		int MAX = 10;

		int[][] array2 = new int[HEIGHT][WIDTH];
		array2 = Generate.generateArray(array2, MIN, MAX);
		int[] result = getPostionOfAbsMin(array2);

		// Show results
		// " + 1" is convertion from computer-read to human-read
		ShowOnLabel.showValueOnLabel(result[0] + 1, jLabel_outputRowExercise17Part2, "Row: ");
		ShowOnLabel.showValueOnLabel(result[1] + 1, jLabel_outputColumnExercise17Part2, "Column: ");
		ShowOnTable.showMatrix(array2, jTable2);
    }//GEN-LAST:event_calculate17_jButttonActionPerformed

    private void accept67_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept67_jButtonActionPerformed
		int[] a = new int[20];
		a = Generate.generateArray(a, 1, 100);
		int[] b = new int[10];
		b = Generate.generateArray(b, 1, 100);
		int[] c = new int[15];
		c = Generate.generateArray(c, 1, 100);

		int min_a = getMinOfArray(a);
		int min_b = getMinOfArray(b);
		int min_c = getMinOfArray(c);
		double avarage = (min_a + min_b + min_c) / 3;

		// Show arrays
		ShowOnLabel.showValueOnLabel(a, jLabel16, "a: ");
		ShowOnLabel.showValueOnLabel(b, jLabel_outputMinB, "b: ");
		ShowOnLabel.showValueOnLabel(c, jLabel_outputCexercise67Part1, "c: ");
		// Show min values
		ShowOnLabel.showValueOnLabel(min_a, jLabel_outputMinAExercise67Part1, "Min a: ");
		ShowOnLabel.showValueOnLabel(min_b, jLabel_outputMinBExercise67Part1, "Min b: ");
		ShowOnLabel.showValueOnLabel(min_c, jLabel_outputMinCExercise67Part1, "Min c: ");
		// Show avarage
		ShowOnLabel.showValueOnLabel(avarage, jLabel_outputAvarageExercise67Part1, "Avarage: ");
    }//GEN-LAST:event_accept67_jButtonActionPerformed

    private void calculate42Part1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate42Part1ActionPerformed
		int[] prices = new int[20];
		prices = Generate.generateArray(prices, 50, 700);

		// Search max and min in prices
		int min = Integer.MAX_VALUE;
		int max = Integer.MIN_VALUE;
		for (int price : prices) {
			if (price > max) {
				max = price;
			}
			if (price < min) {
				min = price;
			}
		}

		// Show results
		ShowOnLabel.showValueOnLabel(prices, jLabel_outputPrices, "Prices: ");
		ShowOnLabel.showValueOnLabel(min, jLabel_outputMin, "Min: ");
		ShowOnLabel.showValueOnLabel(max, jLabel_outputMax, "Max: ");
    }//GEN-LAST:event_calculate42Part1ActionPerformed

    private void jButton_accept17Part1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_accept17Part1ActionPerformed
		// Input
		String input = jTextField_input.getText();
		try {
			double value = InputFromTextField.getFromDoubleTextField(jTextField_input);
			array17[last_array17_index] = value;
			last_array17_index++;
		} catch (Exception e) {

		}

		// End of input, work start
		if (last_array17_index >= 8) {
			double sum = 0;
			for (double i : array17) {
				sum += i;
			}
			double avarage = sum / 8;

			// show results
			ShowOnLabel.showValueOnLabel(avarage, jLabel_inputAvarage);
			ShowOnLabel.showValueOnLabel(array17, jLabel_inputArray, "Array: ");

			jButton_accept17Part1.setEnabled(false);
		}
		jLabel_entered17Part1.setText("Entered: " + Integer.toString(last_array17_index));
    }//GEN-LAST:event_jButton_accept17Part1ActionPerformed

    private void jButton_doExercise42Part4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_doExercise42Part4ActionPerformed
		Person[] persons = new Person[3];
		ArrayList<Person> persons_with_big_weight = new ArrayList<Person>();

		// Generate persons
		for (int i = 0; i < persons.length; i++) {
			persons[i] = Generate.generatePerson();
		}

		// Writing persons to file
		String to_write1 = "";
		String to_write2 = "";
		for (Person person : persons) {
			to_write1 += person.toString();

			if (person.getSummary_weight() > 36.0) {
				to_write2 += person.toString();
				persons_with_big_weight.add(person);
			}
		}

		createAndWriteFile("/tmp/file2.txt", "/tmp", "file2.txt", to_write1);
		createAndWriteFile("/tmp/file3.txt", "/tmp", "file3.txt", to_write2);

		// Output
		ShowOnTable.showMatrix(persons_with_big_weight, jTable_outputWeightExercise42Part4);
		ShowOnTable.showMatrix(persons, jTable_outputOtherExercise42Part4);
    }//GEN-LAST:event_jButton_doExercise42Part4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
		ArrayList<Integer> result = new ArrayList<Integer>();
		for (int i = 111; i < 999; i++) {
			if (checkOdd(i) & checkOdd(i / 10) & checkOdd(i / 100)) {
				String stringed_i = Integer.toString(i);
				String stringed_cutted_i
						= String.valueOf(stringed_i.charAt(0)) + String.valueOf(stringed_i.charAt(2));
				int cutted_i = Integer.valueOf(stringed_cutted_i);
				if (i % cutted_i == 0) {
					result.add(i);
				}
			}
		}

		ShowOnLabel.showValueOnLabel(result, jLabel36, "Result: ");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
		String input = "";
		input = jTextField7.getText();
		int input1_int = 0;
		try {
			input1_int = Integer.parseInt(input);
		} catch (Exception e) {

		}
		if (!(5000 < input1_int & input1_int < 30000)) {

		}

		input = jTextField7.getText();
		double input2_double = 0;
		try {
			input2_double = Double.parseDouble(input);
		} catch (Exception e) {

		}
		if (!(0.5 < input2_double & input2_double < 2.5)) {

		}

		input = "";
		input = jTextField7.getText();
		double input3_double = 0;
		try {
			input3_double = Double.parseDouble(input);
		} catch (Exception e) {

		}
		if (!(0.5 < input2_double & input2_double < 2.5)) {

		}

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
		int[][] A = new int[6][6];

		for (int[] a : A) {
			for (int i = 0; i < a.length; i++) {
				a[i] = (int) (Math.random() * 100);
			}
		}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
		String s = jTextField12.getText();
		String regex = "ABC";

		if (s.length() == 0) {
			jLabel44.setText("String is empty");
		} else if (!s.contains(regex)) {
			jLabel44.setText("String doesn't contain ABC");
		} else {
			String replaceStr = "KLMNO";
			String result = s.replaceAll(regex, replaceStr);
			jLabel44.setText(result);
		}
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
		if (countWords == 0) {
			getCountWords();
		} else {
			if (lastWord < countWords - 1) {
				getNextInput();
			} else {
				jTextField13.setEnabled(false);
				jButton11.setEnabled(false);
				getNextInput();

				ArrayList<String> result = new ArrayList<String>();

				for (String string : input) {
					if (result.size() == 0) {
						result.add(string);
					} else if (result.get(0).length() > string.length()) {
						result.clear();
						result.add(string);
					} else if (result.get(0).length() == string.length()) {
						result.add(string);
					}
				}

				ShowOnList.showArrayOnList(input.toArray(), jList1);
				ShowOnList.showArrayOnList(result.toArray(), jList2);
			}
		}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
		getCountWords();
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
		if (lastWord < countWords - 1) {
			getNextInput();
		} else {
			jTextField13.setEnabled(false);
			jButton11.setEnabled(false);
			getNextInput();

			ArrayList<String> result = new ArrayList<String>();

			for (String string : input) {
				if (result.size() == 0) {
					result.add(string);
				} else if (result.get(0).length() > string.length()) {
					result.clear();
					result.add(string);
				} else if (result.get(0).length() == string.length()) {
					result.add(string);
				}
			}

			ShowOnList.showArrayOnList(input.toArray(), jList1);
			ShowOnList.showArrayOnList(result.toArray(), jList2);
		}
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
		String caption = "";
		for (int i = 0; i < 65536; i++) {
			char ch;
			ch = ' ';
			ch = (char) i;
			caption += String.valueOf(ch);
		}

		jTextField15.setText(caption);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
		JOptionPane.showMessageDialog(jMenu1, "Разработчик: ternek");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
		System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

	public void getCountWords() {
		countWords = InputFromTextField.getFromIntTextField(jTextField14);
		jTextField14.setEnabled(false);
		jTextField13.setEnabled(true);
	}

	public void getNextInput() {
		input.add(jTextField13.getText());
		jLabel45.setText("Entered: " + Integer.toString(lastWord + 1));
		lastWord++;
	}

	public boolean checkOdd(int number) {
		return number % 2 == 1;
	}

	public void exercise67strings(JTextField jTextField, JLabel label) {
		String input = jTextField.getText();
		String output = input;

		// Formating a input string
		for (int i = 0; i < input.length(); i++) {
			Integer number = tryParse(String.valueOf(input.charAt(i)));
			if (number != null) {
				// Enter a space
				output = replaceAt(input, i, number.toString() + " ");
			}
		}

		label.setText(output);
	}

	public static String replaceAt(String str, int index, String ch) {
		return str.substring(0, index) + ch + str.substring(index + 1);
	}

	public static Integer tryParse(String text) {
		try {
			return Integer.parseInt(text);
		} catch (NumberFormatException e) {
			return null;
		}
	}

	public static int getMinOfArray(int[] array) {
		int min = Integer.MAX_VALUE;
		for (int i : array) {
			min = Math.min(min, i);
		}
		return min;
	}

	public static int[] getPostionOfAbsMin(int[][] array) {
		int[] result = new int[2];
		int min = Integer.MAX_VALUE;

		for (int i = 0; i < array.length; i++) {
			for (int j = 0; j < array[i].length; j++) {
				if (Math.abs(array[i][j]) < Math.abs(min)) {
					result[0] = i;
					result[1] = j;
					min = array[i][j];
				}
			}
		}

		return result;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;

				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Mian.class
					.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Mian.class
					.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Mian.class
					.getName()).log(java.util.logging.Level.SEVERE, null, ex);

		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Mian.class
					.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Mian().setVisible(true);
			}
		});
	}

	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accept67_jButton;
    private javax.swing.JButton calculate17_jButtton;
    private javax.swing.JButton calculate42Part1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_accept17Part1;
    private javax.swing.JButton jButton_acceptExercise17Part3;
    private javax.swing.JButton jButton_acceptExercise42Part3;
    private javax.swing.JButton jButton_acceptExercise67Part3;
    private javax.swing.JButton jButton_doExercise17Part4;
    private javax.swing.JButton jButton_doExercise42Part4;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_captionOutputMatrixExercise42aPart2;
    private javax.swing.JLabel jLabel_entered17Part1;
    private javax.swing.JLabel jLabel_exercise17Part1;
    private javax.swing.JLabel jLabel_exercise17Part3;
    private javax.swing.JLabel jLabel_exercise17Part4;
    private javax.swing.JLabel jLabel_exercise42Part1;
    private javax.swing.JLabel jLabel_exercise42Part3;
    private javax.swing.JLabel jLabel_exercise42Part4;
    private javax.swing.JLabel jLabel_exercise42aPart2;
    private javax.swing.JLabel jLabel_exercise67Part3;
    private javax.swing.JLabel jLabel_guess17Part1;
    private javax.swing.JLabel jLabel_inputArray;
    private javax.swing.JLabel jLabel_inputAvarage;
    private javax.swing.JLabel jLabel_output1Exercise67Part3;
    private javax.swing.JLabel jLabel_output2Exercise67Part3;
    private javax.swing.JLabel jLabel_output3Exercise67Part3;
    private javax.swing.JLabel jLabel_outputAvarageExercise67Part1;
    private javax.swing.JLabel jLabel_outputCaptionWeightExercise42Part4;
    private javax.swing.JLabel jLabel_outputCexercise67Part1;
    private javax.swing.JLabel jLabel_outputColumnExercise17Part2;
    private javax.swing.JLabel jLabel_outputExercise17Part3;
    private javax.swing.JLabel jLabel_outputExercise42Part3;
    private javax.swing.JLabel jLabel_outputMax;
    private javax.swing.JLabel jLabel_outputMin;
    private javax.swing.JLabel jLabel_outputMinAExercise67Part1;
    private javax.swing.JLabel jLabel_outputMinB;
    private javax.swing.JLabel jLabel_outputMinBExercise67Part1;
    private javax.swing.JLabel jLabel_outputMinCExercise67Part1;
    private javax.swing.JLabel jLabel_outputOtherCaptionExercise42Part4;
    private javax.swing.JLabel jLabel_outputPrices;
    private javax.swing.JLabel jLabel_outputRowExercise17Part2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Eexercise42Part1;
    private javax.swing.JPanel jPanel_Exercise17Part1;
    private javax.swing.JPanel jPanel_Exercise67Part1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTabbedPane jTabbedPane_Part1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_outputExercise17Part4;
    private javax.swing.JTable jTable_outputMatrixExercise42aPart2;
    private javax.swing.JTable jTable_outputOtherExercise42Part4;
    private javax.swing.JTable jTable_outputWeightExercise42Part4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField_input;
    private javax.swing.JTextField jTextField_input1Exercise67Part3;
    private javax.swing.JTextField jTextField_input2Exercise67Part3;
    private javax.swing.JTextField jTextField_input3ExercisePart3;
    private javax.swing.JTextField jTextField_inputStringExercise17Part3;
    private javax.swing.JTextField jTextField_inputStringExercise42Part3;
    // End of variables declaration//GEN-END:variables
}

class Person {

	String secondName;
	int count_of_stuff;
	double summary_weight;

	public Person(String family, int count_of_stuff, double summary_weight) {
		this.secondName = family;
		this.count_of_stuff = count_of_stuff;
		this.summary_weight = summary_weight;
	}

	public String getSecondName() {
		return secondName;
	}

	public int getCount_of_stuff() {
		return count_of_stuff;
	}

	public double getSummary_weight() {
		return summary_weight;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	public void setCount_of_stuff(int count_of_stuff) {
		this.count_of_stuff = count_of_stuff;
	}

	public void setSummary_weight(double summary_weight) {
		this.summary_weight = summary_weight;
	}

	@Override
	public String toString() {
		return secondName + "   " + count_of_stuff + "   " + summary_weight + "\n";
	}

}
